[ADD] src

diff --git a/src b/src
--- a/src
+++ b/src
@@ -1,4 +1,5 @@
 # -*- mode: sh; -*-
+
 if [ -z "$VIRTUAL_ENV_PROMPT" ]; then
     source .venv/bin/activate
 fi
@@ -8,13 +9,17 @@ OLD_PS1="$PS1"
 PS1="($VIRTUAL_ENV_PROMPT) "'\[\e]0;'"tmux-macros"'\a\]\[\e[1;32m\]\u@\h\[\e[0m\]:\[\e[1;34m\]\W\[\033[00m\]\$ '
 clear
 
-
-
 alias emacs="execnohup emacs; unalias emacs; history -s execnohup emacs"
 alias rmcache='find -type d -iname __pycache__ -execdir rm -rfv \{} \; 2> /dev/null'
 
 source ~/src/.fzf-history
 source ~/src/.gitprojectrc --python
+
+## usage: __cleanup
+function __cleanup {
+    jbackup compress tmux-macros
+}
+trap __cleanup EXIT
 
 ## usage: _test [MOD] [ARG ...]
 function _test {
@@ -40,7 +45,6 @@ function create-stub {
     test -n "$module" || return 0
     basedpyright --createstub "$module"
 }
-
 
 history -c
 HISTFILE="$VIRTUAL_ENV/.bash_history"
